import Head from "next/head";
import Navbar from "../src/component/navbar";
import LandPage from "../src/component/home";
import Footer from "../src/component/footer";


export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://fonts.googleapis.com/css?family=Lemonada&display=swap" rel="stylesheet"></link>
            </Head>

            <Navbar />
            <LandPage />
            <Footer />
        </>
    );
}
